// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtXgl8ByPRriCtCeEnP_JZ6wRqTUnsuQE',
    appId: '1:948647832460:web:c08d35248285971eeb44a9',
    messagingSenderId: '948647832460',
    projectId: 'farfromhome-ef888',
    authDomain: 'farfromhome-ef888.firebaseapp.com',
    storageBucket: 'farfromhome-ef888.firebasestorage.app',
    measurementId: 'G-YPPRVQ5K4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtehBSSbcv3rI93cKcrafMNpB78ZXQ3yE',
    appId: '1:948647832460:android:a4b3409fbf68007ceb44a9',
    messagingSenderId: '948647832460',
    projectId: 'farfromhome-ef888',
    storageBucket: 'farfromhome-ef888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLmuZTVsBM3u-89BHSM1HWijQTfoxo3JM',
    appId: '1:948647832460:ios:5180ac610d35b78feb44a9',
    messagingSenderId: '948647832460',
    projectId: 'farfromhome-ef888',
    storageBucket: 'farfromhome-ef888.firebasestorage.app',
    iosBundleId: 'com.example.farFromHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLmuZTVsBM3u-89BHSM1HWijQTfoxo3JM',
    appId: '1:948647832460:ios:5180ac610d35b78feb44a9',
    messagingSenderId: '948647832460',
    projectId: 'farfromhome-ef888',
    storageBucket: 'farfromhome-ef888.firebasestorage.app',
    iosBundleId: 'com.example.farFromHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtXgl8ByPRriCtCeEnP_JZ6wRqTUnsuQE',
    appId: '1:948647832460:web:13dde8f3fa8394b6eb44a9',
    messagingSenderId: '948647832460',
    projectId: 'farfromhome-ef888',
    authDomain: 'farfromhome-ef888.firebaseapp.com',
    storageBucket: 'farfromhome-ef888.firebasestorage.app',
    measurementId: 'G-QQPVNQWQG4',
  );
}
